/**
 * Alert Fatigue Buster - Initial State & Mock Telemetry Dataset
 */
window.ALERT_DATA = {
  stats: {
    incomingAlerts: 2481,
    actionableAlerts: 37,
    noiseReductionPercent: 98.5,
    activeIncidentsCount: 4,
    criticalAlertsCount: 2,
    mttrSeconds: 252, // 4m 12s
    ingressVelocity: 142.8,
    fatigueAbsorptionPercent: 91.4,
    droppedAlerts: 2267,
    decisionLatencyMs: 11.8,
    activeDedupePool: 63
  },
  
  alerts: [
    {
      id: "ALT-9042",
      fingerprint: "e4f8a91c",
      timestamp: "10:34:12",
      relativeTime: "12s ago",
      service: "payment-gateway",
      cluster: "us-east-prod-k8s",
      namespace: "production",
      severity: "CRITICAL",
      title: "PostgresConnectionPoolExhausted",
      message: "Connection pool utilization > 98% for 45s across 8 poolers. Active threads blocked.",
      status: "TRIGGERED",
      group: "GRP-DB-POOL-01",
      occurrences: 142,
      suppressed: false,
      deduped: false,
      actionable: true,
      labels: { env: "prod", region: "us-east-1", tier: "p0" }
    },
    {
      id: "ALT-9041",
      fingerprint: "b21a78ff",
      timestamp: "10:34:05",
      relativeTime: "19s ago",
      service: "checkout-api",
      cluster: "us-east-prod-k8s",
      namespace: "production",
      severity: "HIGH",
      title: "HTTP5xxRateSpike",
      message: "HTTP 502 Bad Gateway response rate exceeded 4.5% threshold on /api/v2/checkout.",
      status: "TRIGGERED",
      group: "GRP-DB-POOL-01",
      occurrences: 89,
      suppressed: false,
      deduped: true,
      actionable: true,
      labels: { env: "prod", endpoint: "/api/v2/checkout" }
    },
    {
      id: "ALT-9040",
      fingerprint: "c3d9021e",
      timestamp: "10:33:48",
      relativeTime: "36s ago",
      service: "inventory-worker",
      cluster: "us-east-prod-k8s",
      namespace: "production",
      severity: "MEDIUM",
      title: "KafkaConsumerLagExceeded",
      message: "Consumer group 'inv-stock-sync' lag is 14,200 msgs on partition 4.",
      status: "SUPPRESSED",
      group: "GRP-KAFKA-LAG",
      occurrences: 310,
      suppressed: true,
      deduped: true,
      actionable: false,
      labels: { topic: "stock-updates", partition: "4" }
    },
    {
      id: "ALT-9039",
      fingerprint: "98fa103b",
      timestamp: "10:33:15",
      relativeTime: "1m ago",
      service: "auth-service",
      cluster: "eu-west-prod-k8s",
      namespace: "auth-core",
      severity: "LOW",
      title: "RedisLatencyP99Warning",
      message: "Redis cache get operation p99 elevated to 14ms (baseline 2ms).",
      status: "BATCHED",
      group: "GRP-CACHE-JITTER",
      occurrences: 54,
      suppressed: true,
      deduped: true,
      actionable: false,
      labels: { cache_cluster: "redis-auth-01" }
    },
    {
      id: "ALT-9038",
      fingerprint: "11de89cc",
      timestamp: "10:32:44",
      relativeTime: "2m ago",
      service: "ingress-nginx",
      cluster: "us-east-prod-k8s",
      namespace: "ingress-system",
      severity: "CRITICAL",
      title: "UpstreamTimedOut",
      message: "Upstream timeout communicating with payment-gateway pod 10.244.3.18:8080.",
      status: "TRIGGERED",
      group: "GRP-DB-POOL-01",
      occurrences: 198,
      suppressed: false,
      deduped: true,
      actionable: true,
      labels: { upstream: "payment-gateway" }
    },
    {
      id: "ALT-9037",
      fingerprint: "7a6b2901",
      timestamp: "10:31:50",
      relativeTime: "3m ago",
      service: "recommendation-ml",
      cluster: "us-central-k8s",
      namespace: "ml-serving",
      severity: "INFO",
      title: "ModelInferenceBatchWarmup",
      message: "Batch inference model model-v4.1 loaded in 1.4s.",
      status: "RESOLVED",
      group: "GRP-ML-WARM",
      occurrences: 12,
      suppressed: true,
      deduped: true,
      actionable: false,
      labels: { model: "rec-v4" }
    }
  ],

  alertGroups: [
    {
      id: "GRP-DB-POOL-01",
      title: "Cascading Postgres Pool Exhaustion & Checkout 502s",
      highestSeverity: "CRITICAL",
      leadService: "payment-gateway",
      affectedServices: ["payment-gateway", "checkout-api", "ingress-nginx", "order-tracker"],
      rawAlertsCount: 429,
      actionableAlertsCount: 1,
      noiseReductionRatio: "99.7%",
      reductionPercent: 99.7,
      temporalWindow: "15m sliding",
      rootCauseSummary: "Postgres primary max connections reached; downstream callers timing out.",
      fingerprint: "fp-pg-pool-0198a",
      status: "ACTIVE",
      createdTime: "18m ago",
      incidentId: "INC-1042"
    },
    {
      id: "GRP-KAFKA-LAG",
      title: "Temporal Consumer Lag Flapping on Inventory Topic",
      highestSeverity: "MEDIUM",
      leadService: "inventory-worker",
      affectedServices: ["inventory-worker", "warehouse-sync"],
      rawAlertsCount: 310,
      actionableAlertsCount: 0,
      noiseReductionRatio: "100%",
      reductionPercent: 100.0,
      temporalWindow: "30m sliding",
      rootCauseSummary: "Periodic batch ingestion caused temporary buffer saturation. Auto-clearing.",
      fingerprint: "fp-kafka-lag-773a",
      status: "SUPPRESSED_AUTO",
      createdTime: "32m ago",
      incidentId: null
    },
    {
      id: "GRP-CACHE-JITTER",
      title: "Redis Micro-Latency Spikes (Auth Cluster 01)",
      highestSeverity: "LOW",
      leadService: "auth-service",
      affectedServices: ["auth-service"],
      rawAlertsCount: 185,
      actionableAlertsCount: 0,
      noiseReductionRatio: "100%",
      reductionPercent: 100.0,
      temporalWindow: "10m sliding",
      rootCauseSummary: "Background memory compaction run in redis node 02. No user impact.",
      fingerprint: "fp-redis-comp-22b",
      status: "BATCHED_QUIET",
      createdTime: "45m ago",
      incidentId: null
    },
    {
      id: "GRP-K8S-EVICT",
      title: "Ephemeral Pod Rescheduling Burst on Node worker-pool-04",
      highestSeverity: "HIGH",
      leadService: "kube-controller",
      affectedServices: ["kube-controller", "analytics-cron", "log-collector"],
      rawAlertsCount: 156,
      actionableAlertsCount: 2,
      noiseReductionRatio: "98.7%",
      reductionPercent: 98.7,
      temporalWindow: "20m sliding",
      rootCauseSummary: "Disk pressure eviction on worker-pool-04. Pods gracefully re-scheduled.",
      fingerprint: "fp-k8s-evict-54c",
      status: "MONITORING",
      createdTime: "52m ago",
      incidentId: "INC-1039"
    }
  ],

  incidents: [
    {
      id: "INC-1042",
      title: "Database Connection Cascade on postgres-primary",
      severity: "CRITICAL",
      status: "INVESTIGATING",
      startTime: "14:32:08 UTC",
      duration: "18m ago",
      owner: "Alex Rivera (Lead SRE)",
      leadService: "payment-gateway",
      impact: "Checkout & Payment authorization (14.2% failure rate)",
      description: "Cascading connection pool failure on postgres-primary impacting downstream checkout and payment authorization services.",
      alertsCount: 429,
      actionableCount: 1,
      runbookStatus: "In Progress (Step 3/5)",
      warRoomUrl: "#war-room-1042"
    },
    {
      id: "INC-1039",
      title: "Node worker-pool-04 Disk Pressure Evictions",
      severity: "HIGH",
      status: "MITIGATED",
      startTime: "13:54:10 UTC",
      duration: "52m ago",
      owner: "Jordan Chen (Infra SRE)",
      leadService: "kube-controller",
      impact: "Internal batch analytics delay (0 customer impact)",
      description: "Worker node disk exceeded 85% utilization triggering cron job pod rescheduling.",
      alertsCount: 156,
      actionableCount: 2,
      runbookStatus: "Completed",
      warRoomUrl: "#war-room-1039"
    }
  ]
};
